package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 21 12:15:35 PKT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Type_VendorLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Type_VendorLOVImpl() {
    }
}

